
package InterfaceView;


public class PanelMateri extends javax.swing.JPanel {


    public PanelMateri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("MATERI ZAKAT FITRAH\nHukum zakat fitri adalah wajib bagi setiap muslim menurut pendapat yang terkuat. Para ulama yang berpendapat demikian menyatakan kewajiban menunaikan zakat fitri tercakup dalam perintah Allah ta’ala \ndi surat Al Baqarah ayat 43,\n\nوَآتُوا الزَّكَاةَ\n\n“Tunaikanlah zakat”.\n\nAdapun dalil dari hadits-hadits nabi shallallahu ‘alaihi wa sallam menyatakan hal yang sama. Abdullah bin Umar radhiallahu anhuma mengatakan, “Rasulullah shallallahu ‘alaihi wa sallam memerintahkan kami \nagar menunaikan zakat fitri sebelum kaum muslimin berangkat menuju lapangan untuk melaksanakan shalat ‘id.” (Shahih. HR. Muslim). \n\nBeliau radhiallahu anhuma berkata, “Rasulullah shallallahu ‘alaihi wa sallam mewajibkan zakat fitri dengan satu sha kurma, atau satu sha gandum kepada setiap muslim, baik yang berstatus budak atau merdeka, \npria atau wanita, kanak-kanak maupun dewasa” (Shahih. HR. Bukhari). Beliau juga mengatakan, “Rasulullah shallallahu ‘alaihi wa sallam mewajibkan zakat fitri, berupa satu sha’ kurma kering atau gandum kering. \n\n(kewajiban) ini bagi kaum muslimin, budak maupun orang merdeka, laki-laki maupun wanita, anak kecil maupun orang dewasa. Dan beliau memerintahkan agar ditunaikan sebelum orang-orang berangkat shalat.\n”(Shahih. HR. Bukhari & Muslim). Ibnu Abbas radhiallahu anhuma mengatakan, “Rasulullah shallallahu ‘alaihi wa sallam mewajibkan zakat fitri untuk menyucikan orang yang berpuasa dari perbuatan yang menggugurkan\npahala puasa, perbuatan atau ucapan jorok dan sebagai makanan bagi orang miskin. Siapa yang menunaikannya sebelum shalat maka zakatnya diterima. Dan barangsiapa yang menunaikannya setelah shalat hal itu \nhanya terhitung layaknya sedekah biasa” (Hasan. HR. Abu Daud).\n\nDalil-dalil di atas menegaskan bahwa hukum zakat fitri adalah wajib.\n\n\nBaca selengkapnya https://muslim.or.id/26035-fikih-ringkas-seputar-zakat-fitri.html\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
