
package InterfaceView;

public class PanelCredit extends javax.swing.JPanel {

    /**
     * Creates new form PanelCredit
     */
    public PanelCredit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(809, 460));
        setMinimumSize(new java.awt.Dimension(809, 460));
        setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Aplikasi ZaFitTion merupakan aplikasi konsep yang dibuat untuk memudahkan para petugas penyaluran zakat fitrah oleh Masjid AR. Fachruddin UMM \ndalam mendata atau merekam semua kegiatan baik pemasukan maupun penyaluran (distribusi) zakat fitrah. Aplikasi ini masih berupa konsep yang mana terdapat \nsebagian fungsi yang belum berjalan sebagaimana fungsinya (hanya berupa penggambaran). Demikian aplikasi ini dibuat untuk memenuhi tugas besar \nPemrograman Berorientasi Objek kami.");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 130, 680, 150);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Fadhil  Abdurrahman M.     (201810370311272)");
        add(jLabel6);
        jLabel6.setBounds(370, 400, 440, 30);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Melin Inko Nadia                  (201810370311260)");
        add(jLabel5);
        jLabel5.setBounds(370, 370, 440, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Minhatul Aghistnah              (201810370311254) ");
        add(jLabel4);
        jLabel4.setBounds(370, 340, 440, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Naufal Farras D. W.             (201810370311233) ");
        add(jLabel3);
        jLabel3.setBounds(370, 310, 440, 30);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        add(jLabel2);
        jLabel2.setBounds(0, 20, 810, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ramadhan.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 809, 455);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
