
package InterfaceView;

public class View extends javax.swing.JFrame {

    PanelInput inputP;
    PanelStatus statusP;
    PanelMateri materiP;
    PanelCredit creditP;
    
    public View() {
        initComponents();
        inputP = new PanelInput();
        statusP = new PanelStatus();
        materiP = new PanelMateri();
        creditP = new PanelCredit();
        
        linkPanel.add(inputP);
        linkPanel.add(statusP);
        linkPanel.add(materiP);
        linkPanel.add(creditP);
        
        inputP.setVisible(false);
        statusP.setVisible(false);
        materiP.setVisible(false);        
        creditP.setVisible(true);
        
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zakatInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        status = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        materi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        linkPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 51, 0));
        setMinimumSize(new java.awt.Dimension(1081, 695));
        getContentPane().setLayout(null);

        zakatInput.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        zakatInput.setMaximumSize(new java.awt.Dimension(100, 100));
        zakatInput.setPreferredSize(new java.awt.Dimension(100, 100));
        zakatInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                zakatInputMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ZAKAT MASUK");

        javax.swing.GroupLayout zakatInputLayout = new javax.swing.GroupLayout(zakatInput);
        zakatInput.setLayout(zakatInputLayout);
        zakatInputLayout.setHorizontalGroup(
            zakatInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zakatInputLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );
        zakatInputLayout.setVerticalGroup(
            zakatInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zakatInputLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        getContentPane().add(zakatInput);
        zakatInput.setBounds(15, 139, 195, 74);

        status.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        status.setMaximumSize(new java.awt.Dimension(100, 100));
        status.setPreferredSize(new java.awt.Dimension(100, 100));
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statusMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STATUS DISTRIBUSI");

        javax.swing.GroupLayout statusLayout = new javax.swing.GroupLayout(status);
        status.setLayout(statusLayout);
        statusLayout.setHorizontalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusLayout.setVerticalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(status);
        status.setBounds(15, 229, 195, 74);

        materi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        materi.setMaximumSize(new java.awt.Dimension(100, 100));
        materi.setPreferredSize(new java.awt.Dimension(100, 100));
        materi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                materiMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MATERI");

        javax.swing.GroupLayout materiLayout = new javax.swing.GroupLayout(materi);
        materi.setLayout(materiLayout);
        materiLayout.setHorizontalGroup(
            materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materiLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        materiLayout.setVerticalGroup(
            materiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(materi);
        materi.setBounds(15, 319, 195, 74);

        linkPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder()));
        linkPanel.setLayout(new javax.swing.BoxLayout(linkPanel, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(linkPanel);
        linkPanel.setBounds(238, 139, 809, 460);

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 2, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Admin ZaFitTion (Concept)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(238, 16, 553, 41);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 0));
        jLabel5.setText("Masjid AR. Fachruddin Universitas Muhammadiyah Malang");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(238, 100, 465, 21);

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("\"Zakat Fitrah Distribution\"");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(238, 66, 355, 25);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo__1559516210_38090.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(15, 16, 200, 100);

        credits.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        credits.setForeground(new java.awt.Color(0, 255, 255));
        credits.setText("Credits");
        credits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creditsMousePressed(evt);
            }
        });
        getContentPane().add(credits);
        credits.setBounds(15, 409, 58, 22);

        jCalendar1.setMaximumSize(new java.awt.Dimension(198, 163));
        getContentPane().add(jCalendar1);
        jCalendar1.setBounds(15, 447, 208, 176);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/masjidumm.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1060, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zakatInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zakatInputMousePressed
        inputP.setVisible(true);
        statusP.setVisible(false);
        materiP.setVisible(false);
        creditP.setVisible(false);        
    }//GEN-LAST:event_zakatInputMousePressed

    private void statusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMousePressed
        inputP.setVisible(false);
        statusP.setVisible(true);
        materiP.setVisible(false);
        creditP.setVisible(false);        
    }//GEN-LAST:event_statusMousePressed

    private void materiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materiMousePressed
        inputP.setVisible(false);
        statusP.setVisible(false);
        materiP.setVisible(true);
        creditP.setVisible(false);        
    }//GEN-LAST:event_materiMousePressed

    private void creditsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsMousePressed
        inputP.setVisible(false);
        statusP.setVisible(false);
        materiP.setVisible(false);
        creditP.setVisible(true); 
    }//GEN-LAST:event_creditsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel credits;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel linkPanel;
    private javax.swing.JPanel materi;
    private javax.swing.JPanel status;
    private javax.swing.JPanel zakatInput;
    // End of variables declaration//GEN-END:variables
}
